# Generated by Django 5.0.6 on 2024-06-17 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='image_url',
            new_name='imageurl',
        ),
    ]
