# Generated by Django 4.2.11 on 2024-10-01 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_bid_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='listing',
        ),
    ]
